branchName: "/${issue.title[0,25]}/#${issue.number}"
gitSafeReplacementChar: "_"
defaultBranch: "develop"
autoCloseIssue: true
commentMessage: "Branch ${branchName} created for issue: ${issue.title}"
branches:
  - label: add
    prefix: add
